### ISSUE TITLE
`modeltime_calibrate()` Unable to Calibrate a Linear Regression Model (R 4.3.1) - `.pred_res` column returned

### ISSUE THREAD

**Issue by domorev** [business-science/modeltime#228] opened 2023-06-27 17:29 UTC
The latest version of tidyverse's predict function now returns .pred_res column instead of .pred. Because of that Modeltime is unable to calibrate the model and returns the following error:
```R
+   modeltime_calibrate(new_data = testing(splits), quiet = FALSE)
Error: ℹ In argument: `.pred = ifelse(is.na(.pred), optins, .pred)`.
Caused by error:
! object '.pred' not found
```
This is the output from predict():
```R
> lm_predictions <- workflow_fit_lm %>% 
+   predict(new_data = testing(splits))
Warning message:
In predict.lm(object = object$fit, newdata = new_data, type = "response") :
  prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases
> 
> # Typically, predictions are returned in a tibble with a `.pred` column
> lm_predictions
# A tibble: 56 × 1
   .pred_res
       <dbl>
 1      51.9
 2      63.8
 3      45.8
 4      25.4
 5      14.3
 6      14.3
 7      24.7
 8      29.2
 9      83.8
10      65.8
# ℹ 46 more rows
# ℹ Use `print(n = ...)` to see more rows
```

**Comment by mdancho84** [comment] 2023-06-27 17:54
I have committed a fix. Please in a fresh Rstudio session run:
``` r
remotes::install_github("business-science/modeltime", dependencies = TRUE)
```

Then retry the TS Jumpstart codes.

**Comment by domorev** [comment] 2023-06-28 02:51
Updated modeltime and ran it in a fresh session. Now produces a different error. Please see the screenshot attached.

![modeltime_error](https://github.com/business-science/modeltime/assets/95126193/153a86b4-bf9f-4943-ac94-cf14a0f3f44f)

**Comment by domorev** [comment] 2023-06-28 02:52
```R
> workflow_fit_lm |> modeltime_calibrate(new_data = testing(splits), quiet = FALSE)
Error: Can't subset columns that don't exist.
✖ Column `.pred_res` doesn't exist.

```

**Comment by mdancho84** [comment] 2023-06-28 02:57
Not sure. Difficult to resolve since I can't reproduce and all tests are passing both locally and through GH actions.

**Comment by mdancho84** [comment] 2023-06-28 02:59
Also a modeltime table should be piped into modeltime_calibrate(). But the error will probably be the same.

**Comment by mdancho84** [comment] 2023-06-28 03:01
Probably what happens is downstream it's passed the forecast but now another error crips up. 

So ultimately I need to figure out how to replicate the error or otherwise will need your help to create the fix.

**Comment by domorev** [comment] 2023-06-28 03:27
Happy to help, Matt. By the way, I just re-ran the code under R 4.2. and it works. So, there must be something R version specific. Are you able to install R 4.3.1. at your end to try it?

**Comment by domorev** [comment] 2023-06-28 03:27
![image](https://github.com/business-science/modeltime/assets/95126193/22f9905b-afb0-41fb-9db6-a4d0b9b47d77)

**Comment by mdancho84** [comment] 2023-06-28 09:49
Ok that is interesting. Let me try installing R 4.3 and see if I can replicate. 

Give me a couple days since I have multiple things I'm juggling work-wise. Maybe this weekend. 

For now proceed with R 4.2 or lower until I have a chance to fix.

**Comment by mdancho84** [comment] 2023-07-03 14:13
This should be fixed now in the development version of `modeltime`. Install with:
``` r
remotes::install_github("business-science/modeltime", dependencies = TRUE)
```

**Comment by mdancho84** [comment] 2023-07-03 14:14
Here's me re-running the TS Jumpstart with R4.3+ and the dev version of modeltime. 
![image](https://github.com/business-science/modeltime/assets/13734662/02b47343-fe27-4c4c-8c4a-ca8a80965398)

**Comment by mdancho84** [comment] 2023-07-03 14:20
I'm closing- this fix is complete.

**Closed by mdancho84** 2023-07-03 14:20 UTC

**Comment by domorev** [comment] 2023-07-03 15:15
Thanks, Matt!

I will check it tomorrow from my end.

By the way, I am loving the Time Series course. Wish I had known about it a
year ago when I had a spare term (forced study break).

I am doing Big Data subject at Uni this term - we only have one week
dedicated to Time Series, I doubt it will be as thorough as your course. 😎

Cheers,

Alexei

**Comment by mdancho84** [comment] 2023-07-03 15:21
You got it. New version of modeltime is on its way to CRAN. Should be up there shortly. 

Enjoy the course. There's nothing like it.

**Comment by joranE** [comment] 2023-07-03 19:47
FYI [this](https://github.com/tidymodels/parsnip/issues/985) just recently discovered parsnip issue is probably related.

**Comment by mdancho84** [comment] 2023-07-03 19:50
Thanks for this. The latest version of modeltime should now work until the tidymodels team implements the .pred_res fix.

**Comment by domorev** [comment] 2023-07-04 05:27
Hey Matt,

All good - it is working now!

Cheers,

Alexei
