### ISSUE TITLE
plot_modeltime_forecast() function doesn't get .line_color parameter

### ISSUE THREAD

**Issue by lucazav** [business-science/modeltime#155] opened 2022-01-23 13:00 UTC
I'm trying to change the color of the time-series line in a plot I get using the `plot_modeltime_forecast()` function.
In the help of the function I read I can also pass `timetk::plot_time_series()` parameters. So I tried to pass the `.line_color = "#3366FF"` parameter to the function, but the line color doesn't change.
Is there another way to change the color of the line?

**Comment by mdancho84** [comment] 2022-01-23 13:39
This is odd. So you have a reproducible example?

**Comment by lucazav** [comment] 2022-01-23 15:08
Just use this CSV file: [ts_forecast.csv](https://github.com/business-science/modeltime/files/7920704/ts_forecast.csv)
Here the script:

```
library(readr)
library(dplyr)
library(modeltime)


forecast_df <- read_csv("C:/temp/ts_forecast.csv")

forecast_df %>%
    mutate(
        date = as.POSIXct(date)
    ) %>% 
    mutate(
        .model_id   = ifelse(is.na(conf_lo), NA, 1),
        .model_desc = ifelse(is.na(conf_lo), "ACTUAL", "model1"),
        .key        = ifelse(is.na(conf_lo), "actual", "prediction"),
        .index      = date,
        .value      = value,
        .conf_lo    = conf_lo,
        .conf_hi    = conf_hi
    ) %>% 
    select(
        .model_id,
        .model_desc,
        .key,
        .index,
        .value,
        .conf_lo,
        .conf_hi   
    ) %>% 
    plot_modeltime_forecast(
        .line_color = "#3366FF",
        .conf_interval_fill = "lightblue",
        .interactive = TRUE
    )
```

The result is the following:

![image](https://user-images.githubusercontent.com/6104437/150684964-3fc3e520-8d9f-414e-8f76-29f66373142c.png)

I'm using `modeltime 1.1.1`.

**Comment by lucazav** [comment] 2022-01-23 15:31
Also `.color_var` from `plot_time_series()` is not working in the `plot_modeltime_forecast()` function:

```
forecast_df %>%
    mutate(
        date = as.POSIXct(date)
    ) %>% 
    mutate(
        quarter = as.factor(quarters(date))
    ) %>% 
    mutate(
        .model_id   = ifelse(is.na(conf_lo), NA, 1),
        .model_desc = ifelse(is.na(conf_lo), "ACTUAL", "model1"),
        .key        = ifelse(is.na(conf_lo), "actual", "prediction"),
        .index      = date,
        .value      = value,
        .conf_lo    = conf_lo,
        .conf_hi    = conf_hi
    ) %>% 
    select(
        .model_id,
        .model_desc,
        .key,
        .index,
        .value,
        .conf_lo,
        .conf_hi,
        quarter
    ) %>% 
    plot_modeltime_forecast(
        #.line_color = "#3366FF",
        .conf_interval_fill = "lightblue",
        .interactive = TRUE,
        .color_var = quarter
    )
```

I'm getting the following error:

> Error in timetk::plot_time_series(.data = data_prepared, .date_var = .index,  : 
>   formal argument ".color_var" matched by multiple actual arguments

It seems there is a problem with passing each `plot_time_series()` function's parameter.

**Comment by mdancho84** [comment] 2022-01-24 10:46
I've reviewed. The reason is that the .color_var is hard coded to the .model_desc column. 

So changing the .color_var is not having an effect on the plot.

**Comment by mdancho84** [comment] 2022-09-08 15:31
Closing this to keep modeltime issues tidy.

**Closed by mdancho84** 2022-09-08 15:31 UTC
