### ISSUE TITLE
namespace ‘vctrs’ 0.2.4 is already loaded, but >= 0.3.0 is required 

### ISSUE THREAD

**Issue by stepminer** [business-science/modeltime#35] opened 2020-09-03 14:46 UTC
> library(tidymodels)
Error: package or namespace load failed for ‘tidymodels’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.4.6 is being loaded, but >= 0.4.7 is required
> library(modeltime)
Error: package or namespace load failed for ‘modeltime’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘vctrs’ 0.2.4 is already loaded, but >= 0.3.0 is required
> library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘vctrs’ 0.2.4 is already loaded, but >= 0.3.0 is required
> library(lubridate)

Attaching package: ‘lubridate’

The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

> library(timetk)
Error: package or namespace load failed for ‘timetk’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘dplyr’ 0.8.5 is already loaded, but >= 1.0.0 is required

**Comment by mdancho84** [comment] 2020-09-03 15:11
You may need to upgrade R >= 4.0.0. It's showing `rlang >= 0.4.7` and `vctrs >= 0.3.0` are required. Your R is likely too old for these upgraded packages, which is preventing newer versions of `rlang` and `vctrs` from downloading.

**Comment by stepminer** [comment] 2020-09-04 11:22
Thanks, I Downloaded R version 4.0.2 and reinstalled the package modeltime. Still having issues:
> library(tidymodels)
Error in library(tidymodels) : there is no package called ‘tidymodels’
> library(modeltime)
> library(tidyverse)
Error in library(tidyverse) : there is no package called ‘tidyverse’
> library(lubridate)

**Comment by mdancho84** [comment] 2020-09-04 11:33
Yes, you need to install these libraries - try `devtools::install_github("business-science/modeltime", dependencies = TRUE)`

This will install the latest development version of `modeltime`, which has a few improvements and will install all of the dependencies associated with it.

**Comment by spsanderson** [comment] 2020-09-04 12:05
Looks like those libraries are not installed but I thought the install of modeltime would do that,

**Comment by mdancho84** [comment] 2020-09-04 12:13
No, the tidymodels and tidyverse are suggested, not required. To get them you’ll need to install them specifically or to use dependencies = TRUE. 

What is installed is several packages that tidymodels and tidyverse contain like dplyr and parsnip. But the meta packages are not installed.

**Comment by spsanderson** [comment] 2020-09-04 12:41
Gotcha

**Comment by stepminer** [comment] 2020-09-04 13:06
The script does not work. I will try to install the packages manually.
devtools::install_github("business-science/modeltime", dependencies = TRUE)
Error in loadNamespace(name) : there is no package called ‘devtools’

**Comment by spsanderson** [comment] 2020-09-04 13:18
Do you have devtools installed?

**Comment by spsanderson** [comment] 2020-09-04 13:20
maybe try something like 

```
if(!require(pacman)) {install.packages("pacman")}
pacman::p_load(
"tidyverse","tidyquant","lubridate","modeltime"
)
```

**Comment by stepminer** [comment] 2020-09-04 14:29
Thanks I was able to install the packages manually and test the ModelTime Tutorial. It performed successfully on the m750 data, except for the EARTH model although I also manually installed the package.
> models_tbl <- modeltime_table(
+     model_fit_arima_no_boost,
+     model_fit_arima_boosted,
+     model_fit_ets,
+     model_fit_prophet,
+     model_fit_lm,
+     wflw_fit_mars
+ )
Error in eval_tidy(xs[[j]], mask) : object 'wflw_fit_mars' not found

Otherwise its Great.
![Modeltime m750](https://user-images.githubusercontent.com/70709034/92250386-66c7d280-ee99-11ea-8e95-b907cd4aabca.jpeg)

**Comment by spsanderson** [comment] 2020-09-04 15:13
It is telling you the object does not exist in the environment

**Comment by mdancho84** [comment] 2020-09-21 01:34
Closing - This appears to be due to the user needing to install packages, which is a local issue to the user and not a bug with the modeltime software.

**Closed by mdancho84** 2020-09-21 01:34 UTC
