### ISSUE TITLE
code breaking update: cores > cores_available

### ISSUE THREAD

**Issue by Steviey** [business-science/modeltime#110] opened 2021-06-03 14:03 UTC
**Ubuntu 1.16 LTS, R 4.x, modeltime 0.6.0**

Error in if (cores > cores_available) cores <- cores_available : 
  missing value where TRUE/FALSE needed
It seems like a dependency-issue to parallel, while I'm actually not using it (VM).
Earlier versions of my code, incl. modeltime were functional.
Currently trying to reproduce...
... cores<-parallel::detectCores(all.tests=TRUE,logical = TRUE) dedetects "NA" on my virtual machine, which is kind of typically, according to the vignette of parallel. They mention "hope"... https://www.rdocumentation.org/packages/parallel/versions/3.6.2/topics/detectCores
...Nope, that's a hard-coded one.

frequency = 26 observations per 1 quarter
Error in if (cores > cores_available) cores <- cores_available : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In guerrero(x, lower, upper) :
  Guerrero's method for selecting a Box-Cox parameter (lambda) is given for strictly positive data.
2: In guerrero(x, lower, upper) :
  Guerrero's method for selecting a Box-Cox parameter (lambda) is given for strictly positive data.
3: In guerrero(x, lower, upper) :
  Guerrero's method for selecting a Box-Cox parameter (lambda) is given for strictly positive data.
4: In guerrero(x, lower, upper) :
  Guerrero's method for selecting a Box-Cox parameter (lambda) is given for strictly positive data.
5: In guerrero(x, lower, upper) :
  Guerrero's method for selecting a Box-Cox parameter (lambda) is given for strictly positive data.
6: In guerrero(x, lower, upper) :
  Guerrero's method for selecting a Box-Cox parameter (lambda) is given for strictly positive data.
7: In guerrero(x, lower, upper) :
  Guerrero's method for selecting a Box-Cox parameter (lambda) is given for strictly positive data.
8: In guerrero(x, lower, upper) :
  Guerrero's method for selecting a Box-Cox parameter (lambda) is given for strictly positive data.
9: In guerrero(x, lower, upper) :
  Guerrero's method for selecting a Box-Cox parameter (lambda) is given for strictly positive data.
10: In guerrero(x, lower, upper) :
  Guerrero's method for selecting a Box-Cox parameter (lambda) is given for strictly positive data.
```
     █
  1. ├─global::bAlgos(i, f, "prediction") ~/R/daScript.R:59737:12
  2. │ ├─base::do.call(...) ~/R/daScript.R:59377:12
  3. │ └─(function (seed, dataset, metric, control, f, i, algo, only_one_predictor_exception, ...
  4. │   └─`%>%`(...) ~/R/daScript.R:44099:16
  5. ├─modeltime::modeltime_forecast(., new_data = myFuture, actual_data = allData)
  6. ├─modeltime::modeltime_refit(., model_table, data = allData)
  7. ├─modeltime:::modeltime_refit.mdl_time_tbl(., model_table, data = allData)
  8. │ └─modeltime::control_refit()
  9. │   └─modeltime:::control_modeltime_objects(...)
 10. └─(function () ...
 11.   └─lobstr::cst() ~/R/daScript.R:13:25
8: stop() at daScript.R#43575

```
Is there a way to bring the amount of cores in the right namespace manually,
or do I have to downgrade?

**Comment by mdancho84** [comment] 2021-06-03 14:11
Do you have a reproducible example?

**Comment by Steviey** [comment] 2021-06-04 21:01
Not at the moment. The new parallel processing integration is defensively buggy... have to downgrade.

**Comment by AlbertoAlmuinha** [comment] 2021-06-04 21:05
What problems have you encountered, or in what situations have you seen problems?? Could you be a little more specific?

**Comment by Steviey** [comment] 2021-06-04 21:16
I described it in my first comment. The core-detection does not work in every case, this leads to "missing value where TRUE/FALSE needed", especially on virtual machines, and probably when sharing cpu for example with a h2o-instance (my assumption).

**Comment by mdancho84** [comment] 2021-06-05 00:00
This is definitely something we need to look into. Ideally I'd like to totally bypass anything with parallel processing if the user specifies allow_par = FALSE. We will take a look. May need some assistance reproducing since I wasn't able to replicate with my tests.

**Comment by Steviey** [comment] 2021-06-05 03:11
Like I said, the case **cores_available=NA** can't be replicated on every arbitrary system.
It depends on specific factors described in the vignette of package parallel.

Therefore it makes no sense, spending hours of code extraction of my 50k+ line script, to try to provide a reproducible example, which will not deliver (the bug) on a dedicated server. 

The rest of it is easy. The exception 'cores > cores_available' has to be excluded from 'allow_par = FALSE'.

**Comment by mdancho84** [comment] 2021-06-05 10:35
OK, this should be fixed with the latest development version. Let me know and we can close this out. 
```
remotes::install_github('business-science/modeltime')
```

**Comment by Steviey** [comment] 2021-06-05 12:52
This seems to work.

**Closed** 2021-06-05 12:53 UTC
